// 02-react-app/index.js
import * as React from "react";
import * as ReactDOM from "react-dom";
import singleSpaReact from "single-spa-react";
import { registerApplication, start } from "single-spa";
import Root from "./Root";

const app = singleSpaReact({
  React,
  ReactDOM,
  rootComponent: Root,
});

registerApplication({
  name: "react-app",
  app,
  activeWhen: ["/"],
  customProps: {
    authToken: "sfdyfs90987sd9sd9f0sd-9fsdfsd",
  },
});

start();

// 02-angular-app/index.ts
import { singleSpaAngular } from 'single-spa-angular'
import { registerApplication, start } from 'single-spa'
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic'
import { NgZone } from '@angular/core';
import { AppModule } from './src/app.module'
import { ReplaySubject } from 'rxjs'

export const singleSpaPropsSubject = new ReplaySubject(1)

const app = singleSpaAngular({
  bootstrapFunction(singleSpaProps) {
    singleSpaPropsSubject.next(singleSpaProps)
    return platformBrowserDynamic().bootstrapModule(AppModule)
  },
  template: '<app-root>',
  NgZone,
})

registerApplication({
  name: 'angular-app',
  app,
  activeWhen: ['/'],
  customProps: {
    authToken: 'asdf7s98df7f6sd909f87sdf0'
  }
})

start()
