// 04-vue-app/Root.vue
<template>
  <div>
    <router-link to="/vue" style="padding: 16px; display: inline-block;">Vue Home</router-link>
    <router-link to="/vue/subroute" style="padding: 16px; display: inline-block;">Vue Sub Route</router-link>
    <router-link to="/angular" style="padding: 16px; display: inline-block;">Leave Vue</router-link>
    <div>Vue app is mounted</div>
    <router-view></router-view>
  </div>
</template>

// 04-react-navbar/Root.jsx
import { BrowserRouter, Link } from "react-router-dom";

export default function Root(props) {
  const linkStyle = {
    padding: "16px",
    display: "inline-block",
  };

  return (
    <BrowserRouter basename="/">
      <Link to="/" style={linkStyle}>
        Home
      </Link>
      <Link to="/react" style={linkStyle}>
        React
      </Link>
      <Link to="/vue" style={linkStyle}>
        Vue
      </Link>
      <Link to="/angular" style={linkStyle}>
        Angular
      </Link>
    </BrowserRouter>
  );
}
