// 08-settings/Root.jsx
import { getNavHeightPx } from "navbar";

export default function Root() {
  // Not below the navbar
  // return <h1>React settings page</h1>

  // Below the navbar
  // Example use of cross-microfrontend imports
  return (
    <h1 style={{ marginTop: getNavHeightPx() + "px" }}>React settings page</h1>
  );
}

// 08-home/Root.vue
<template>
  <!-- Wrong: The home page won't be below the fixed navbar -->
  <!-- <h1>Vue Home Page</h1> -->

  <!-- Correct: position home below the navbar, using cross-microfrontend imports  -->
  <BelowNav>
    <h1>Vue Home page</h1>
  </BelowNav>
</template>
<script>
import { BelowNav } from "navbar";

export default {
  components: {
    BelowNav,
  },
};
</script>
